// <auto-generated />
using System;
using DataBaseRepository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseRepository.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    [Migration("20260927185819_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DataBaseRepository.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DataBaseRepository.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("AppUseTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Avatar")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CurrentLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableNottify")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLanguageCode");

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("DataBaseRepository.Models.UserData", b =>
                {
                    b.HasOne("DataBaseRepository.Models.Language", "CurrentLanguage")
                        .WithMany()
                        .HasForeignKey("CurrentLanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
